set nocompatible              " be iMproved, required
filetype off                  " required
set number
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab " use spaces instead of tabs.
set smarttab " let's tab key insert 'tab stops', and bksp deletes tabs.
set shiftround " tab / shifting moves to closest tabstop.
set autoindent " Match indents on new lines.
set smartindent " Intellegently dedent / indent new lines based on rules.
syntax on
filetype plugin indent on
set backspace=indent,eol,start

" set the runtime path to include Vundle and initialize
" " set rtp+=~/.vim/bundle/Vundle.vim
" " call vundle#begin()
" " " let Vundle manage Vundle, required
" " Plugin 'VundleVim/Vundle.vim'
" "
" " " Keep Plugin commands between vundle#begin/end.
" " Plugin 'tpope/vim-fugitive'
" " Plugin 'christoomey/vim-system-copy'
" " Plugin 'git://git.wincent.com/command-t.git'
" " Plugin 'file:///home/gmarik/path/to/plugin'
" " Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" " " Plugin 'ascenator/L9', {'name': 'newL9'}
" " Bundle 'gmarik/vundle'
" " Bundle 'flazz/vim-colorschemes'
" " Bundle 'kien/ctrlp.vim'
" " " All of your Plugins must be added before the following line
" " call vundle#end()            " required
" " filetype plugin indent on    " required
" "
" "
" "
" " " To ignore plugin indent changes, instead use:
" " "filetype plugin on
" " "
" " " Brief help
" " " :PluginList       - lists configured plugins
" " " :PluginInstall    - installs plugins; append `!` to update or just
" " :PluginUpdate
" " " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " " :PluginClean      - confirms removal of unused plugins; append `!` to
" " auto-approve removal
" " "
" " " see :h vundle for more details or wiki for FAQ
" " " Put your non-Plugin stuff after this line
